### ISSUE TITLE
BigQuery table not partitioned

### ISSUE THREAD

**Issue by JorritSalverda** [cloudflare/GCS-To-Big-Query#9]
In order to make using the logs from bigquery cost efficient the table created by the cloud function should use partitioning per date. That way your query won't go through years of data when you're only querying for today.

**Comment by shagamemnon** [comment]
@JorritSalverda we're working on it here: #8

**Comment by JLLeitschuh** [comment]
Can this be re-opened as the PR that was going to resolve this was closed?
